_BASE_: Base-PanopticDeepLab-OS16.yaml
MODEL:
  WEIGHTS: "/Users/sahilmodi/Projects/Git_Repos/detectron2/projects/Panoptic-DeepLab/models/model_panoptic_deeplap_dsconv_cityscapes.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  DEVICE: "cpu"
  BACKBONE:
    NAME: "build_resnet_deeplab_backbone"
  RESNETS:
    DEPTH: 50
    NORM: "BN"
    RES5_MULTI_GRID: [1, 2, 4]
    STEM_TYPE: "deeplab"
    STEM_OUT_CHANNELS: 128
    STRIDE_IN_1X1: False
  PANOPTIC_DEEPLAB:
    USE_DEPTHWISE_SEPARABLE_CONV: True
  SEM_SEG_HEAD:
    USE_DEPTHWISE_SEPARABLE_CONV: True
    NUM_CLASSES: 2
    NORM: "BN"
  INS_EMBED_HEAD:
    NORM: "BN"
DATASETS:
  TRAIN: ("roofai_18k_facets_panoptic_train",)
  TEST: ("roofai_18k_facets_panoptic_val",)
SOLVER:
  MAX_ITER: 150000
  IMS_PER_BATCH: 2
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (800,)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 800
  MAX_SIZE_TRAIN: 800
  MAX_SIZE_TEST: 800
  CROP:
    SIZE: (800,800)
